# Generated by Django 4.2.7 on 2024-04-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_items",
            field=models.TextField(default="Default Order Items"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                    ("paypal", "PayPal"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
