# Generated by Django 4.2.7 on 2024-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_completedorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_items",
        ),
        migrations.AddField(
            model_name="order",
            name="order_items",
            field=models.ManyToManyField(to="catalog.item"),
        ),
    ]
