# Generated by Django 4.2.7 on 2024-04-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_item_remove_order_order_items_order_order_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactmessage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="title",
        ),
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(default="Default Name", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="Default City", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="county",
            field=models.CharField(default="Default County", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="eircode",
            field=models.CharField(default="0000000", max_length=7),
        ),
        migrations.AddField(
            model_name="order",
            name="house",
            field=models.CharField(default="Default House", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="street",
            field=models.CharField(default="Default Street", max_length=255),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(default="Default Name", max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                    ("paypal", "PayPal"),
                ],
                default="credit_card",
                max_length=20,
            ),
        ),
    ]
