# Generated by Django 4.2.7 on 2024-04-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_remove_contactmessage_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="county",
        ),
        migrations.RemoveField(
            model_name="order",
            name="eircode",
        ),
        migrations.RemoveField(
            model_name="order",
            name="house",
        ),
        migrations.RemoveField(
            model_name="order",
            name="street",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                    ("paypal", "PayPal"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
